server:
  port: 8086
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  datasource:
    username: postgres
    password: 977515747
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_fastfood
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: ADMINSERVICE
debug: true
