server:
  port: 8085
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: ORDERSERVICE
  datasource:
    username: postgres
    password: 977515747
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_fastfood
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

debug: true


